version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: aladin-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aladin
      MYSQL_USER: aladin_user
      MYSQL_PASSWORD: aladin_pass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: